const mongoose = require('mongoose');

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },
    phone: { type: String, default: '', trim: true },
    country: { type: String, default: '', trim: true },
    bio: { type: String, default: '', trim: true, maxlength: 320 },
    language: { type: String, default: 'English', trim: true },
    timezone: { type: String, default: 'Africa/Lagos', trim: true },
    avatarUrl: { type: String, default: '', trim: true },
    notificationSettings: {
      taskAlerts: { type: Boolean, default: true },
      securityAlerts: { type: Boolean, default: true },
      payoutAlerts: { type: Boolean, default: true },
      marketing: { type: Boolean, default: false },
    },
    passwordHash: { type: String, required: true },
    role: {
      type: String,
      enum: ['user', 'admin'],
      default: 'user',
      index: true,
    },
    walletBalance: { type: Number, default: 0 },
    withdrawableBalance: { type: Number, default: 0 },
    depositTotalUsd: { type: Number, default: 0 },
    extraTaskSlots: { type: Number, default: 0 },
    lastDepositAt: { type: Date, default: null },
    streak: { type: Number, default: 0 },
    tier: { type: String, default: 'Tier 1' },
    registrationFeeUsd: { type: Number, default: 0 },
    registrationPaymentMethod: {
      type: String,
      enum: ['bank_transfer', 'paypal', 'crypto'],
      default: null,
    },
    registrationPaymentReference: { type: String, default: '' },
    registrationPaymentAmountUsd: { type: Number, default: 0 },
    registrationPaidAt: { type: Date, default: null },
    tierUpgradedAt: { type: Date, default: null },
    tierUpgradePaymentMethod: {
      type: String,
      enum: ['bank_transfer', 'paypal', 'crypto'],
      default: null,
    },
    tierUpgradePaymentReference: { type: String, default: '' },
    tierUpgradePaymentAmountUsd: { type: Number, default: 0 },
    aiBotFeeUsd: { type: Number, default: 0 },
    aiBotEnabled: { type: Boolean, default: false },
    aiBotPaymentMethod: {
      type: String,
      enum: ['bank_transfer', 'paypal', 'crypto', 'wallet'],
      default: null,
    },
    aiBotPaymentReference: { type: String, default: '' },
    aiBotPaymentTxHash: { type: String, default: '' },
    aiBotPaymentProofFile: { type: String, default: '' },
    aiBotVerificationStatus: {
      type: String,
      enum: ['unverified', 'verified', 'rejected'],
      default: 'unverified',
    },
    aiBotVerifiedAt: { type: Date, default: null },
    aiBotVerifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    aiBotActivatedAt: { type: Date, default: null },
    aiBotExpiresAt: { type: Date, default: null },
    aiBotSubscriptionMonths: { type: Number, default: 1 },
    aiBotLastCheckpointAt: { type: Date, default: null },
    aiBotNextCheckpointAt: { type: Date, default: null },
    aiBotDailyRunsDate: { type: String, default: '' },
    aiBotDailyRunsCount: { type: Number, default: 0 },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

module.exports = mongoose.model('User', userSchema);
